### ISSUE TITLE
Menu option not showing when extension installed

### ISSUE THREAD

**Issue by PeterGeelen** [mjisaak/mvp-docs-learn-champion-extension#9]
Hello,

I installed the extension in Edge, Version 87.0.664.57.
The extension icon is showing grey (i don't know if it should be blue or not...)

But as explained in the description of the app in the store, the context menu "Copy Link address with CreatorID" should be visible, but I don't see the context menu item.

Do I need to fix any option or setting in my browser to make it work?
Any suggestion for troubleshooting?

**Comment by mjisaak** [comment]
Hi Peter,

it is correct, that the extension is showing a grey symbol since it doesn't require any access:
![image](https://user-images.githubusercontent.com/8446917/101792368-ec949300-3b04-11eb-8153-f88f178a580f.png)

Did you enter your Creator Id within the options already? Otherwise, the context menu won't be visible:

![image](https://user-images.githubusercontent.com/8446917/101792646-3aa99680-3b05-11eb-9d18-84c3c0e2306c.png)

Now you should see the menu on all links that are tracked by the docs & learn champion program. To verify it, just go to https://docs.microsoft.com/en-us/ and right-click on "Documentation":

![image](https://user-images.githubusercontent.com/8446917/101792959-98d67980-3b05-11eb-8e3b-13d8c60b67c3.png)

**Comment by PeterGeelen** [comment]
Hello, 

thanks for the rapid response...

I've got my CreatorIDs entered.
![mvp_bar_issue1](https://user-images.githubusercontent.com/16639202/101829635-9854d780-3b33-11eb-9089-5e5a6009e80f.PNG)

and when I right click the Documentation link as you suggested, the context menu does not show
![mvp_bar_issue2](https://user-images.githubusercontent.com/16639202/101829693-b15d8880-3b33-11eb-9e10-0b994a66582e.PNG)

**Comment by PeterGeelen** [comment]
In Chrome it works. In Edge not.

**Comment by mjisaak** [comment]
@PeterGeelen Hm, someone else also mentioned he had to reinstall it on edge in order to get it working again. Can you please try that? I will check what could be the issue here and try to improve the extension.

**Comment by PeterGeelen** [comment]
Yes, it works after removing it, reinstalling it then killing edge and restarting Edge.

But even on docs only some of the URL links have the option to use the menu item.
That's another discussion.

**Comment by mjisaak** [comment]
Should be fixed with release 1.2.2
